services:
  imageop:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${EXTERNAL_PORT:-3080}:${PORT:-3080}"
    volumes:
      - ../data/uploads:/app/data/uploads
      - ../data/compressed:/app/data/compressed
      - ../data/resized:/app/data/resized
      - ../.env:/app/.env  # 挂载业务配置文件
    restart: always
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3080/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

